# https://www.dartlang.org/guides/language/analysis-options
analyzer:

  language:


# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    - camel_case_types
    - hash_and_equals
    - unrelated_type_equality_checks
    - valid_regexps
  
